name: WeatherForecast
options:
  postGenCommand: scripts/postGen.sh

  deploymentTarget:
    iOS: '15.0'

  xcodeVersion: 15.4

# SETTINGS

settings: 
  base:
    ALWAYS_SEARCH_USER_PATHS: NO
    BUILD_LIBRARY_FOR_DISTRIBUTION: YES
    CODE_SIGN_IDENTITY: iPhone Developer
    CODE_SIGN_IDENTITY[sdk=iphoneos*]: iPhone Developer
    CODE_SIGN_STYLE: Manual
    CURRENT_PROJECT_VERSION: 1
    ENABLED_BITCODE: NO
    ENABLE_TESTABILITY: NO
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    MARKETING_VERSION: 1.0.0
    ONLY_ACTIVE_ARCH: YES
    PRODUCT_NAME: $(TARGET_NAME)
    PROVISIONING_PROFILE: 
    PROVISIONING_PROFILE_SPECIFIER:
    SKIP_INSTALL: NO

# SCHEMES

schemes:
  WeatherForecast:
    build:
      targets:
        WeatherForecast: all
        WeatherForecastTests: [test]
    test:
      gatherCoverageData: true
      coverageTargets:
        - WeatherForecast
      targets:
        - name: WeatherForecastTests
          parallelizable: false
      environmentVariables:
        - variable: FB_REFERENCE_IMAGE_DIR
          value: $(SOURCE_ROOT)/WeatherForecast/Tests/ReferenceImages
          isEnabled: true
        - variable: IMAGE_DIFF_DIR
          value: $(SOURCE_ROOT)/WeatherForecast/Tests/FailureDiffs
          isEnabled: true
  WeatherForecast-Sample:
    build:
      targets:
        WeatherForecast-Sample: all
    run:
      additionalOptions:
        zoobinObjects: true
      commandLineArguments:
        "-FIRDebugEnabled" : true
        "-FIRAnalyticsDebugEnabled" : true
      config: Debug
      debugEnabled: true
  WeatherForecastUITests:
    build:
      targets:
        WeatherForecast-Sample: all
        WeatherForecastUITests: all
    test:
      gatherCoverageData: true
      targets:
        - name: WeatherForecastUITests
          parallelizable: false


# TARGETS

targets:
  WeatherForecast:
    type: framework
    platform: iOS
    sources: 
      - path: WeatherForecast/Classes
      - path: WeatherForecast/Assets
    settings:
      base:
        INFOPLIST_FILE: WeatherForecast/Classes/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vitorneves.WeatherForecast
        ENABLE_TESTABILITY: YES
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
    postBuildScript:
      - script: scripts/swiftlint.sh
        name: Swiftlint

  WeatherForecast-Sample:
    type: application
    platform: iOS
    sources: 
      - path: WeatherForecast-Sample
        name: WeatherForecast-Sample
    settings:
      base:
        INFOPLIST_FILE: WeatherForecast-Sample/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vitorneves.WeatherForecast-Sample
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_IDENTITY[sdk=iphoneos*]: iPhone Developer
        PROVISIONING_PROFILE: 
        PROVISIONING_PROFILE_SPECIFIER:
        BUILD_LIBRARY_FOR_DISTRIBUTION: NO
    dependencies:
      - target: WeatherForecast
        codeSign: true
        embed: true
    postBuildScript:
      - script: scripts/swiftlint.sh
        name: Swiftlint
    
  WeatherForecastTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: WeatherForecast
        embed: true
    sources: 
      - path: WeatherForecast/Tests
        excludes: 
          - "FailureDiffs/*"
          - "ReferenceImages/*"
          - "ReferenceImages_64/*"
        name: WeatherForecastTests
    postBuildScript:
      - script: scripts/swiftlint.sh
        name: Swiftlint
    settings:
      base:
        INFOPLIST_FILE: WeatherForecast/Tests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vitorneves.WeatherForecastTests
  WeatherForecastUITests:
    type: bundle.ui-testing
    platform: iOS
    dependencies:
      - target: WeatherForecast-Sample
        embed: true
    sources: 
      - path: WeatherForecastUITests
        name: WeatherForecastUITests
    settings:
      base:
        INFOPLIST_FILE: WeatherForecastUITests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vitorneves.WeatherForecastUITests
aggregateTargets:
  XCFramework:
    buildScripts:
      - script: scripts/buildxcframework.sh
        name: Generate XCFramework
